### ISSUE TITLE
parameter versus property

### ISSUE THREAD

**Issue by hklages** [svrooij/sonos-api-docs#10]
I suggest to rename "parameter" to "property" for the methods (in table header). 
Reading parameter leads to create calls ..... .SetMute(0, true, 'Master') instead of using object with the properties

**Comment by svrooij** [comment]
What page do you mean? Url?

Documentation of Sonos-ts or the generic soap documentation?

I’m such a fan of TypeScript because then it would just not compile if you code it wrong

**Comment by hklages** [comment]
>  What page do you mean? Url?
All servcies for instance [this](https://svrooij.io/node-sonos-ts/sonos-device/services/av-transport-service.html#addmultipleuristoqueue)

> Documentation of Sonos-ts or the generic soap documentation?
Both but I put the issue only to sonos-api-docs. 

I guess you only have to change the template. 
Input --> Input as object
parameter --> property

![parameter](https://user-images.githubusercontent.com/17273119/104887714-0cbd3a80-596c-11eb-824f-c18ffddcf9c5.png)
