### ISSUE TITLE
Supplemental event properties

### ISSUE THREAD

**Issue by svrooij** [svrooij/sonos-api-docs#38]
@svrooij just did the re-generation, thank you!
One thing I noted was, it wiped away rendering control service's `HeightChannelLevel` that I added in this pr, which makes sense. It doesn't come back in the discovery doc, though it does actually get returned in the real world (I tested this).

Along these lines, is there a mechanism in place to supplement events properties that don't come back in the discovery doc?

_Originally posted by @jkossis in https://github.com/svrooij/node-sonos-ts/issues/172#issuecomment-1315269049_

**Comment by svrooij** [comment]
@jkossis there is no such way (at the moment). But I'm not saying that we should not create something like that.

The strange thing is dat currently it does show some EQ values in the [event proerties](https://svrooij.io/sonos-api-docs/services/rendering-control.html#event-variables) like `NightMode` or `DialogLevel`. Perhaps this property is added later and isn't supported on the devices I used to generate the documentation with. And the **ARC** is currently not indexed I believe.

Could you try what happens if you index the ARC? If you index the arc (which is good to have anyway) it will create a discovery file for that device and maybe it's in there. 

https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs#sonos-docs-services-ip

If it isn't there, I'll modify the schema to allow addition event properties.

**Comment by svrooij** [comment]
@jkossis you need help with that?

```bash
# Clone repo
# go to correct folder
cd generator/sonos-docs

# install dependencies
npm install

# Execute service discovery (replace IP with arc ip)
./bin/run services 192.168.0.0
```

**Comment by jkossis** [comment]
@svrooij all good, should be able to get that change up in the next few hours.

**Comment by svrooij** [comment]
No worries, don't want to rush you.

**Comment by jkossis** [comment]
@svrooij [here's](https://github.com/svrooij/sonos-api-docs/pull/39) the associated pr.

Unfortunately, it looks like the `HeightChannelLevel` still isn't showing as part of the Arc's discovery definition. 😞

**Comment by svrooij** [comment]
I really find it strange that for the EQ value it does not have the allowed values... That would make this so much easier....

![image](https://user-images.githubusercontent.com/1292510/202019826-2dfc60b5-41ea-488e-bc2f-0747aa0f884c.png)

Anyways, it seems not to be available. I propose a eventProperties array on the [service level in the documentation](https://github.com/svrooij/sonos-api-docs/blob/2b63bd6bb0340e58de991608f70afcf648edb220/docs/documentation.json#L354). do you think that could work?

With something like this:

```json
"eventProperties": [
  { "name": "HeightChannelLevel", "type": "i2"}
]
```

**Comment by svrooij** [comment]
@jkossis sorry I missed your last response, and was enormously busy last week. Will be back behind my computer on Monday. Then I'll add a way to add additional event properties.

**Comment by jkossis** [comment]
All good @svrooij! I appreciate you being willing to take a look at it.
