### ISSUE TITLE
error 714 issue

### ISSUE THREAD

**Issue by amedeopro** [svrooij/sonos-api-docs#42]
Hello when i try to set my URI file:///jffs/settings/savedqueues.rsq#26 with setAVTransportURI i receive this response

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
    <s:Body>
        <s:Fault>
            <faultcode>s:Client</faultcode>
            <faultstring>UPnPError</faultstring>
            <detail>
                <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
                    <errorCode>714</errorCode>
                </UPnPError>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```

i don't what is it and how can i fix this issue. Can you help me?

Thank you

**Comment by svrooij** [comment]
This is not an official Sonos help channel, this documentation on Sonos speakers is made by [us](https://svrooij.io/sonos-api-docs/#contributors) in our free-time.

Your message suggest that you're using [SetTransportURI](https://svrooij.io/sonos-api-docs/services/av-transport.html#setavtransporturi), if you scroll all the way down, it shows the [known upnp errors](https://svrooij.io/sonos-api-docs/services/av-transport.html#custom-errors). `714` means illegal mime-type.

My personal guess is that you cannot use **SetTRansportURI** to start playing a saved queue
 a saved queue. I think you have to:

1. Switch to the playback queue [like this in node](https://github.com/svrooij/node-sonos-ts/blob/322a36d838c4cbdf424a8d2f48142d2d227ba101/src/sonos-device.ts#L645-L647)
2. Add the saved queue to the playback queue.

I hope it helps, but this is all the support I can give you. This issue tracker is for mistakes in the documentation.

**Comment by hklages** [comment]
You can use AddUri: 

```
const uri = "file:///jffs/settings/savedqueues.rsq#26"
await tsCoordinator.AddUriToQueue(uri, 0, true)
```
